# Generated by Django 3.1.6 on 2021-04-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210407_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
    ]
