# Generated by Django 3.1.6 on 2021-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_student_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
