# Generated by Django 3.1.6 on 2021-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='marks',
            field=models.IntegerField(default=10),
        ),
    ]
