# Generated by Django 3.1.6 on 2021-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_course_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
