# Generated by Django 3.1.6 on 2021-04-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_remove_question_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
