# Generated by Django 3.1.6 on 2021-04-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interests',
            new_name='courses',
        ),
    ]
